### ISSUE TITLE
Links not working 

### ISSUE THREAD

**Issue by Ashraf-DS** [BioinfoMachineLearning/GCDM-SBDD#3]
**These given links of files downloading is not working is there any other way to download the files .**

wget http://www.bindingmoad.org/files/biou/every_part_a.zip
wget http://www.bindingmoad.org/files/biou/every_part_b.zip
wget http://www.bindingmoad.org/files/csv/every.csv

**Comment by amorehead** [comment]
Hello. Thank you for informing me of this issue. It seems the Binding MOAD server is no longer operational per https://www.nature.com/articles/s41598-023-29996-w. As such, I have updated the Zenodo record for this repository/paper to now contain these required Binding MOAD dataset files. You can download them using the following (new) README instructions:

```bash
wget https://zenodo.org/record/13375913/files/every_part_a.zip
wget https://zenodo.org/record/13375913/files/every_part_b.zip
wget https://zenodo.org/record/13375913/files/every.csv
```

Let me know if you have any other questions.
