### ISSUE TITLE
Regarding error getting (runtime error) in running train.py

### ISSUE THREAD

**Issue by Ashraf-DS** [BioinfoMachineLearning/GCDM-SBDD#4]
once i have downloaded the data n the folder named "binding_moad"  and preprocessed it  after that total files iside the binding moad i got as follows :- 

![image](https://github.com/user-attachments/assets/9a4bd6f9-413a-4214-be70-c56633a3a45c)

now i am running the train script for new training  :- 
     **"python -u train.py config=configs/bindingmoad_ca_cond_egnn.yml"**

i have also changed the path and all required in config file :-
    
1. i have changed **logdir path as  '/home/administrator/GCDM-SBDD/logs/train'**
2. i have changed **wandb to offline mode** 
3. i have changed **datadir path as - '/home/administrator/GCDM-SBDD/binding_moad/processed_noH_full'**
4. i have changed **smiles_file path as -  '/home/administrator/GCDM-SBDD/binding_moad/processed_noH_full/train_smiles.npy'**

after that i am running  train_script  and i am getting runtime error as follows in the below screenshot given  :-

![image](https://github.com/user-attachments/assets/ef8232d5-472d-4c86-acd5-8aee4d848dfc)

after that i checked the shape of all files in the "processed_noH_full" then got this in the below screenshot :- 

![image](https://github.com/user-attachments/assets/19e5872a-a714-4c9a-8238-f10ba1568e9f)

can you please help on this for resolution asap 
Thank you

**Comment by amorehead** [comment]
Hi, @Ashraf-DS. It seems for some reason your copy of the code is constructing 10-hot (instead of 20-hot) residue type vectors for each pocket amino acid when training on the Binding MOAD dataset. To identify why this is the case, I would recommend setting a breakpoint [here](https://github.com/BioinfoMachineLearning/GCDM-SBDD/blob/ec76034916a42cd5ceb304c98f85074c09f0de6d/dataset.py#L10) and seeing if you can identify the source in this file.

**Comment by Ashraf-DS** [comment]
Hi @amorehead  i have checked the path by inserting breakpoint it seems its taking correct path only see the below screenshot 

![image](https://github.com/user-attachments/assets/b112a44e-3939-4cd6-ad12-ee29314c186b)

Thank you

**Comment by amorehead** [comment]
Hi, @Ashraf-DS. Just following up, were you able to figure out the issue here?

**Comment by amorehead** [comment]
Hi again, @Ashraf-DS. If you have any further issues, please feel free to reach out. In the meantime, I will be closing this issue.
